<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL9u5lnu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL9u5lnu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerL9u5lnu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerL9u5lnu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerL9u5lnu\appProdProjectContainer([
    'container.build_hash' => 'L9u5lnu',
    'container.build_id' => '6ae69733',
    'container.build_time' => 1574018783,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL9u5lnu');
